export const mockSponsors = [
    {
        id: '1',
        sponsor: "Virgin Atlantic",
        location: "Title",
        active: true,
        startDate: "04/15/2025",
        endDate: "06/30/2025",
        order: 1,
        discountAmount: "$50",
        quantity: 100,
        redeem: 500
    },
    {
        id: '2',
        sponsor: "Mexicue",
        location: "Star Store",
        active: true,
        startDate: "05/01/2025",
        endDate: "07/15/2025",
        order: 2,
        discountAmount: "25%",
        quantity: 50,
        redeem: 300
    },
    {
        id: '3',
        sponsor: "Uber Eats",
        location: "Redeem Shop",
        active: false,
        startDate: "03/01/2025",
        endDate: "04/30/2025",
        order: 3,
        discountAmount: "$20",
        quantity: 200,
        redeem: 400
    },
    {
        id: '4',
        sponsor: "Spotify",
        location: "Hot Flash",
        active: true,
        startDate: "05/10/2025",
        endDate: "08/10/2025",
        order: 4,
        discountAmount: "3 months free",
        quantity: 75,
        redeem: 600
    },
    {
        id: '5',
        sponsor: "Airbnb",
        location: "Redeem Shop",
        active: false,
        startDate: "02/15/2025",
        endDate: "04/15/2025",
        order: 5,
        discountAmount: "$100",
        quantity: 30,
        redeem: 1000
    },
    {
        id: '6',
        sponsor: "DoorDash",
        location: "Star Store",
        active: true,
        startDate: "04/20/2025",
        endDate: "06/20/2025",
        order: 6,
        discountAmount: "$15",
        quantity: 150,
        redeem: 350
    },
    {
        id: '7',
        sponsor: "Nike",
        location: "Hot Flash",
        active: true,
        startDate: "05/15/2025",
        endDate: "08/15/2025",
        order: 7,
        discountAmount: "30%",
        quantity: 80,
        redeem: 750
    },
    {
        id: '8',
        sponsor: "Blue Bottle Coffee",
        location: "Star Store",
        active: true,
        startDate: "05/01/2025",
        endDate: "07/01/2025",
        order: 8,
        discountAmount: "Free drink",
        quantity: 200,
        redeem: 250
    },
    {
        id: '9',
        sponsor: "AMC Theaters",
        location: "Title",
        active: true,
        startDate: "06/01/2025",
        endDate: "09/01/2025",
        order: 9,
        discountAmount: "2 tickets for 1",
        quantity: 100,
        redeem: 800
    },
    {
        id: '10',
        sponsor: "Sweetgreen",
        location: "Star Store",
        active: false,
        startDate: "01/15/2025",
        endDate: "04/15/2025",
        order: 10,
        discountAmount: "$15",
        quantity: 150,
        redeem: 350
    },
    {
        id: '11',
        sponsor: "Southwest Airlines",
        location: "Hot Flash",
        active: true,
        startDate: "05/01/2025",
        endDate: "07/31/2025",
        order: 11,
        discountAmount: "10% off flight",
        quantity: 50,
        redeem: 1200
    },
    {
        id: '12',
        sponsor: "Sephora",
        location: "Star Store",
        active: true,
        startDate: "06/15/2025",
        endDate: "09/15/2025",
        order: 12,
        discountAmount: "Free trial kit",
        quantity: 100,
        redeem: 450
    },
    {
        id: '13',
        sponsor: "Apple",
        location: "Title",
        active: false,
        startDate: "03/01/2025",
        endDate: "05/01/2025",
        order: 13,
        discountAmount: "15% off accessories",
        quantity: 75,
        redeem: 900
    },
    {
        id: '14',
        sponsor: "HelloFresh",
        location: "Star Store",
        active: true,
        startDate: "04/15/2025",
        endDate: "07/15/2025",
        order: 14,
        discountAmount: "First box free",
        quantity: 60,
        redeem: 700
    },
    {
        id: '15',
        sponsor: "Hilton Hotels",
        location: "Redeem Shop",
        active: true,
        startDate: "05/01/2025",
        endDate: "10/01/2025",
        order: 15,
        discountAmount: "Free night",
        quantity: 25,
        redeem: 1500
    },
    {
        id: '16',
        sponsor: "Lyft",
        location: "Hot Flash",
        active: true,
        startDate: "05/15/2025",
        endDate: "08/15/2025",
        order: 16,
        discountAmount: "$25 credit",
        quantity: 150,
        redeem: 400
    },
    {
        id: '17',
        sponsor: "Best Buy",
        location: "Title",
        active: false,
        startDate: "02/01/2025",
        endDate: "05/01/2025",
        order: 17,
        discountAmount: "$50 off $200+",
        quantity: 100,
        redeem: 800
    },
    {
        id: '18',
        sponsor: "Equinox",
        location: "Redeem Shop",
        active: true,
        startDate: "05/01/2025",
        endDate: "07/31/2025",
        order: 18,
        discountAmount: "Free week pass",
        quantity: 50,
        redeem: 600
    },
    {
        id: '19',
        sponsor: "REI",
        location: "Hot Flash",
        active: true,
        startDate: "06/01/2025",
        endDate: "09/01/2025",
        order: 19,
        discountAmount: "20% one item",
        quantity: 120,
        redeem: 550
    },
    {
        id: '20',
        sponsor: "Chipotle",
        location: "Redeem Shop",
        active: true,
        startDate: "04/01/2025",
        endDate: "06/30/2025",
        order: 20,
        discountAmount: "Free entrée",
        quantity: 200,
        redeem: 300
    }
];